### PR TITLE
Use jest only

### PR DESCRIPTION
**Pull request by vutran**
This PR removes `jasmine` as it should already be available inside of `jest` itself by calling `jest` in the e2e script. (ref #4 /cc @zhaoshengjun) 

In addition, I moved the tests to a new `__tests__` dir which is `jest`'s default directory which allows us to have a single test script.

### CODE REVIEW

**Comment by TheLarkInn** [comment]
I saw the two PR's you submitted I'm going to set up Travis quick and push to master so we can start getting feedback on tests.

**Comment by TheLarkInn** [comment]
@vutran would you mind adding a travis yaml config file to the base of the project? I've now turned travis integration on against PR's and I would like to verify it's working. What better way than this PR which is already running tests.

**Comment by vutran** [comment]
Just added, I actually have never used selenium with travis so I'm not sure how that is going to work. I'll look into it if it fails.

**Comment by TheLarkInn** [comment]
The results is pretty positive so far. A few failing tests, looking in relationship to maybe jquery api's? Doesn't jest provide some sort of testEnvironment config to assist browser based testing? (I really have limited knowledge so I'm not sure) @zhaoshengjun

**Comment by vutran** [comment]
The e2e test is using `cheerio` which provides a similar interface like `jquery`. However, it looks like the `selenium-webdriver` is what is breaking on travis since it can't open a chrome browser. Perhaps, we can replace that implementation with `phantomjs` since it's headless.

**Comment by TheLarkInn** [comment]
I have setup Saucelabs support, you just need to provide the following information to the travis.yml

``` yaml
addons:
  sauce_connect: true
```

I have setup env vars on travis privately to avoid posting them in the yaml file. 

Otherwise you can use [this document](https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-Sauce-Labs) on travis's page to configure the selenium tests. 

Let me know if this is something you want to pursue, otherwise I'm fine with whatever you think works. :-D

**Comment by vutran** [comment]
@TheLarkInn I haven't forgotten this task. I'm currently looking into the Saucelabs integration but having some difficulties with proxying the local `webpack-dev-server` to saucelabs connect (via [`sauce-connect-launcher`](https://github.com/bermi/sauce-connect-launcher)). Will continue digging but if you have any idea, please drop a line.

**Comment by TheLarkInn** [comment]
No worries if I can help in any way just let me know!!!

**Pull request closed without merging**
