### PR TITLE
Update webpack

### PR DESCRIPTION
**Pull request by comfroels**
This also plugs in the VS code debugger. Had to create a different entry to pass it through `babel-register` for es6 debugging. @TheLarkInn

### CODE REVIEW

**Comment by comfroels** [comment]
I'll look at the build failure later this weekend... Don't know why there's a bunch of ruby failures?

**Comment by TheLarkInn** [comment]
@comfroels Hey, yes I believe this was an attempt to have integration setup, but got abandond by a collaborator to setup saucelabs testing integration. I think maybe we could remove this for now. If you'd like to turn off the tests for it, or rather, remove the travis.yml that is fine. This won't be a published package rather a boilerplate for use. (I think maybe at the most we could ensure that it builds correctly).

**Review by TheLarkInn — COMMENTED** [review]
If you don't want to go through the efforts of removing the .e2e that is okay, I think that really we only need to confirm that it can run webpack successfully after install.

**Comment by comfroels** [comment]
Yeah not a problem, when I get time a little later today, I'll take care of it!

**Comment by comfroels** [comment]
Alright, I have removed the e2e tests.. There actually isn't a `travis.yml` in there. So you might just need to unhook it?

**Comment by comfroels** [comment]
@TheLarkInn Should be good to go if you get rid of the CI build.

**Review by TheLarkInn — APPROVED** [review]

**Comment by TheLarkInn** [comment]
Thank you!! I'll have to try this out tomorrow!

**Comment by comfroels** [comment]
Whoop! First OSS contribution!

**Pull request merged**
